### ISSUE TITLE
Logout issue 

### ISSUE THREAD

**Issue by peererror** [leob/feathers-next#3]
When I login user and refresh the page and then logout the user is signout from client end but after refresh user is still signed in

**Comment by peererror** [comment]
One more thing I noticed that if I login from chrome with user1 and open firefox it shows the usres1 already logged in

**Comment by leob** [comment]
You're an excellent tester! I'll have a look at both.

**Comment by leob** [comment]
@peererror This should be fixed now ... the problem (it took me some time to find out) was as follows:

When you log out, the cookie containing the JWT is cleared, but if you then refresh the page (click refresh in the browser) the server side code (triggered by next.js's "getInitialProps") is trying to re-authenticate using the JWT value in the cookie, *but it does not check if the cookie is empty* ...

So it tries to call authenticate with an empty JWT, and this will actually *succeed* because the way Feathers works is it will then simply create and return a NEW jwt ... which (in this case) is not what we want.

So I now simply check if the JWT from the cookie is empty before trying to authenticate with it.

The code is more convoluted and confusing than I thought but after reading the code 5 times I now again remember how it worked.

And I messed up a bit with the merging (overwriting a previous pull request) but that's all fixed again.

If you agree that this is fixed now then we can close this issue.

**Comment by peererror** [comment]
ok .let me check
